chartmogul/chartmogul-ruby

- README.md
- Move Configuration above Usage.
- Demonstrate how users can find the Ruby usage for different endpoints.
> Make ReadMe Configuration and Usage sections more useful

- README.md
> switch Travis badge, add version badge

- lib/chartmogul/api/actions/custom.rb
Fixes #22 
JIRA: https://chartmogul.atlassian.net/browse/CMRB-16
> Fix subscription cancellation

- changelog.md
- fixtures/vcr_cassettes/ChartMogul_Enrichment_Customer/API_Interactions/merges_customers_using_external_id.yml
- fixtures/vcr_cassettes/ChartMogul_Enrichment_Customer/API_Interactions/merges_customers_using_uuid.yml
- lib/chartmogul/api/actions/custom.rb
- lib/chartmogul/enrichment/customer.rb
- lib/chartmogul/version.rb
- spec/chartmogul/enrichment/customer_spec.rb
Add support for merging Customers using UUIDs or Data Source UUIDs and Customer's external_ids
> Add support for merging customers

- changelog.md
- fixtures/vcr_cassettes/ChartMogul_Enrichment_Customer/API_Interactions/raises_422_for_update_with_invalid_data.yml
- fixtures/vcr_cassettes/ChartMogul_Enrichment_Customer/API_Interactions/updates_customer.yml
- lib/chartmogul/enrichment/customer.rb
- spec/chartmogul/enrichment/customer_spec.rb
Can update customer attributes now according to this docs: https://dev.chartmogul.com/v1.0/reference#update-a-customer
> Add support for updating customers

- changelog.md
- fixtures/vcr_cassettes/ChartMogul_Customer/API_Interactions/correctly_interracts_with_the_API.yml
- fixtures/vcr_cassettes/ChartMogul_Customer/_find_by_external_id/when_external_id_is_provided/returns_matching_user_if_exists.yml
- fixtures/vcr_cassettes/ChartMogul_Customer/_find_by_external_id/when_external_id_is_provided/returns_nil_if_customer_does_not_exist.yml
- lib/chartmogul.rb
- lib/chartmogul/concerns/pageable2.rb
- lib/chartmogul/customer.rb
- lib/chartmogul/version.rb
- spec/chartmogul/customer_spec.rb
> fix Customer: new endpoint has paging as Enrichment (entries...)

- fixtures/vcr_cassettes/ChartMogul_Invoice/API_Interactions/returns_all_invoices_through_list_all_endpoint.yml
- lib/chartmogul/invoice.rb
- lib/chartmogul/version.rb
- spec/chartmogul/invoice_spec.rb
* adding possibility to list invoices across customers/data sources
* includes spec which tests basic query params and result parsing
> Adding List Invoices endpoint with spec

- lib/chartmogul/invoice.rb
- lib/chartmogul/version.rb
* also fixing static `all` on Invoice
> [DP-495] new optional parameter data_source_uuid on Invoice

- .travis.yml
- lib/chartmogul/line_items/one_time.rb
- lib/chartmogul/line_items/subscription.rb
- lib/chartmogul/version.rb
> Add support for transaction_fees_in_cents [ch3030]

- lib/chartmogul/line_items/one_time.rb
- lib/chartmogul/version.rb
- spec/chartmogul/line_items/one_time_spec.rb
Add plan_uuid to one line items.
> Add plan_uuid to one line item [ch3363]

- chartmogul-ruby.gemspec
- lib/chartmogul/version.rb
Updating the faraday dependency to avoid issues like https://github.com/chartmogul/chartmogul-ruby/issues/52#issuecomment-419983457
> Update faraday dependency

- .travis.yml
- README.md
- chartmogul-ruby.gemspec
- pre-commit.example
- spec/spec_helper.rb
I realized we don't have this properly integrated with codeclimate.
> Enable code coverage, add hook example [ch9982]

- spec/chartmogul/plan_group_spec.rb
Fix for https://github.com/chartmogul/chartmogul-ruby/issues/74 issue.
> Fix failing flacky spec

- README.md
- lib/chartmogul.rb
- lib/chartmogul/version.rb
This PR makes the gem's configuration threadsafe to avoid problems in Sidekiq environment.
> Make configuration threadsafe [ch23375]

- lib/chartmogul/csv/uploads/base.rb
- spec/chartmogul/csv/uploads/customer_spec.rb
https://app.clubhouse.io/chartmogul/story/26297/send-csv-files-using-import-api
> Send csv files using Import API [ch26297]

- lib/chartmogul/csv/cancellation.rb
- spec/chartmogul/csv/cancellation_spec.rb
https://app.clubhouse.io/chartmogul/story/26991/cancellation-not-working-in-paypal-dp
> Cancellation not working in PayPal DP [ch26991]

- lib/chartmogul/transactions/payment.rb
- lib/chartmogul/transactions/refund.rb
- lib/chartmogul/version.rb
- spec/chartmogul/transactions/payment_spec.rb
- spec/chartmogul/transactions/refund_spec.rb
Make `amount_in_cents` attribute available in ruby gem.
> Add amount_in_cents to payments for partial payments

- lib/chartmogul/version.rb
Bumping version for a new release.
> Bump version to 1.7.3

- lib/chartmogul/csv/line_items/one_time.rb
- lib/chartmogul/csv/line_items/subscription.rb
- spec/chartmogul/csv/line_items/one_item_spec.rb
- spec/chartmogul/csv/line_items/subscription_spec.rb
Story details: https://app.clubhouse.io/chartmogul/story/33078
> Add transaction_fees_currency to csv/json layer in client library [CH33078]

- changelog.md
- chartmogul-ruby.gemspec
- lib/chartmogul/version.rb
Add deprecation warning about changes in authentication configuration.
> Add deprecation info [#35172]

- README.md
- changelog.md
- lib/chartmogul.rb
- lib/chartmogul/api_resource.rb
- lib/chartmogul/configuration.rb
- lib/chartmogul/version.rb
- spec/chartmogul/api_resource_spec.rb
- spec/chartmogul/configuration_spec.rb
- spec/chartmogul/connection_cache_spec.rb
- spec/chartmogul/retry_spec.rb
- spec/spec_helper.rb
- Introduce single API key instead of account token/secret key combo
- Bump version to 3.0.0
> Introduce new auth method [sc-35172]

- .github/workflows/test.yml
This adds Ruby 3.0 to CI tests as part of the testing matrix.
> Test ruby 3.0 as well

- changelog.md
- lib/chartmogul/version.rb
> Release v4.2.0

- lib/chartmogul.rb
- lib/chartmogul/customer.rb
- lib/chartmogul/opportunity.rb
- spec/chartmogul/customer_spec.rb
- spec/chartmogul/opportunity_spec.rb
- spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/creates_a_opportunity_belonging_to_the_customer_correctly.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/lists_the_opportunities_belonging_to_the_customer_correctly.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Opportunity/API_Actions/creates_a_opportunity_correctly.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Opportunity/API_Actions/destroys_the_opportunity_correctly.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Opportunity/API_Actions/retrieves_a_opportunity_correctly.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Opportunity/API_Actions/retrieves_all_opportunities_correctly.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Opportunity/API_Actions/updates_the_opportunity_correctly_with_the_class_method.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Opportunity/API_Actions/with_pagination/paginates_correctly.yml
closes ticket: https://app.shortcut.com/chartmogul/story/57427/support-opportunities-resource-ruby-client?vc_group_by=day&ct_workflow=all&cf_workflow=500105879
API document: https://www.notion.so/chartmogul/API-endpoints-for-Opportunities-a92323514bf44f89ad2f97ae30cee7f0#6f09cc7a71bc40e69ef65d8d0342d230 
1. Create a opportunity 
```
customer = ChartMogul::Customer.retrieve('cus_3819e09a-50a2-11ee-ada7-9fcf71cd4580')
customer.create_opportunity(
....
)
ChartMogul::Opportunity.create(data)
```
2. Get all opportunities
```
customer = ChartMogul::Customer.retrieve('cus_3819e09a-50a2-11ee-ada7-9fcf71cd4580')
customer.opportunities
ChartMogul::Opportunity.all(customer_uuid: customer_uuid)
```
3. Get an opportunity
```
opportunities = ChartMogul::Opportunity.retrieve('opportunity_uuid')
```
4. …
> feat(sc-57427): Support Opportunities API

- lib/chartmogul/customer.rb
- spec/chartmogul/customer_spec.rb
- spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/unmerges_correctly_with_the_class_method.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/unmerges_correctly_with_the_instance_method.yml
Story details: https://app.shortcut.com/chartmogul/story/62677
This PR adds support for the customer unmerge API endpoint.
> [sc-62677] SDK Unmerge Support - Ruby

- lib/chartmogul/csv/invoice.rb
- spec/chartmogul/csv/invoice_spec.rb
Will depend on https://github.com/chartmogul/platform/pull/23679
> Add collection_method to invoice [sc-65230]

- lib/chartmogul/line_items/subscription.rb
- spec/chartmogul/line_items/subscription_spec.rb
Add support for `proration_type` field for `LineItems -> Subscription.`
> Proration type support for LineItems Subscription

- changelog.md
- lib/chartmogul/subscription.rb
- lib/chartmogul/transactions/payment.rb
- lib/chartmogul/transactions/refund.rb
- lib/chartmogul/version.rb
- spec/chartmogul/subscription_spec.rb
- spec/chartmogul/transactions/payment_spec.rb
- spec/fixtures/vcr_cassettes/ChartMogul_Subscription/API_Interactions/connects_subscriptions.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Subscription/API_Interactions/disconnects_subscriptions.yml
- spec/fixtures/vcr_cassettes/ChartMogul_Transactions_Payment/API_Interactions/correctly_interracts_with_the_API.yml
Story details: https://app.shortcut.com/chartmogul/story/66234
This PR:
* Adds support for the `disconnect_subscriptions` endpoint
* Adds support for the `transaction_fees_in_cents` field on the Transaction object
> [sc-66234] Support disconnecting subscriptions in Ruby library
