chartmogul/chartmogul-ruby

fixtures/vcr_cassettes/ChartMogul_Import_Customer/_find_by_external_id/when_external_id_is_provided/returns_matching_user_if_exists.yml
fixtures/vcr_cassettes/ChartMogul_Import_Customer/_find_by_external_id/when_external_id_is_provided/returns_nil_if_customer_does_not_exist.yml
lib/chartmogul/import/customer.rb
spec/chartmogul/import/customer_spec.rb

I've included a very simple `.find_by_external_id` method in `Import::Customer`.
This would avoid the following pattern for retrieving one particular customer:
```
customer = ChartMogul::Import::Customer.all(external_id:"cus_0001").first
```

Search customer by external_id (Import API)

---

changelog.md
fixtures/vcr_cassettes/ChartMogul_Import_Customer/API_Interactions/correctly_interracts_with_the_API.yml
lib/chartmogul/import/customer.rb
lib/chartmogul/version.rb
spec/chartmogul/import/customer_spec.rb

Now you can send `lead_created_at` and `free_trial_started_at` attributes to assist with ChartMogul's Leads and Trials features. [More information on this here](https://dev.chartmogul.com/v1.0/docs/tracking-leads-and-free-trials-using-the-api).

Add support for lead_created_at and free_trial_started_at fields

---

fixtures/vcr_cassettes/ChartMogul_Enrichment_Customer/API_Interactions/raises_401_if_invalid_credentials.yml
lib/chartmogul.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/errors/unauthorized_error.rb
spec/chartmogul/enrichment/customer_spec.rb

1. Problem: when I have no internet connection and try to get data from CM using this gem, I not handled error:
```
>>  ChartMogul::Enrichment::Customer.all(page: 1, per_page: 50)
NoMethodError: undefined method `[]' for nil:NilClass
```
Reason: exception.response inside of a rescue block is nil => another exception when trying to work with it as with hash:
```
>> (ChartMogul::Enrichment::Customers) »  exception.response
=> nil
```
Solution: change logic of rescue block depending on presence of `exception.response` 
2. Add custom error handler for "401 Unauthorized"

Handle errors of APIResource if exception.response is nil

---

fixtures/vcr_cassettes/ChartMogul_Invoice/API_Interactions/deletes_an_invoice.yml
fixtures/vcr_cassettes/ChartMogul_Invoice/API_Interactions/deletes_an_invoice_with_class_method.yml
fixtures/vcr_cassettes/ChartMogul_Invoice/API_Interactions/raises_error_on_deleting_non-existing_invoice.yml
lib/chartmogul/api/actions/destroy.rb
lib/chartmogul/invoice.rb
lib/chartmogul/version.rb
spec/chartmogul/invoice_spec.rb

* the same as other resources
* because user couldn't do `Invoice.destroy!(uuid)`, and instead they had to first retrieve the invoice, I've added static method `resource.destroy!(uuid: 'uuid')`, which applies also to customers, plans & data sources

[DP-309] support for Delete Invoice

---

changelog.md
lib/chartmogul/errors/chartmogul_error.rb
lib/chartmogul/version.rb
spec/chartmogul/customer_spec.rb

Stops overriding `#message` method of StandardError class.
Uses customer error message.
Fixes tests.
When the error was raised It used to print/log only first `message` argument passed to the class instead of using `#to_s` method.
The reason is that `#message` method was overriden by `attr_accessor: :message` line.

Fix ChartMogul::ChartMogulError class

---

README.md
chartmogul-ruby.gemspec
lib/chartmogul.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/config_attributes.rb
lib/chartmogul/configuration.rb
lib/chartmogul/version.rb
spec/chartmogul/retry_spec.rb
spec/spec_helper.rb

Making use of https://github.com/lostisland/faraday/blob/master/lib/faraday/request/retry.rb
retry request of statuses [429, 500-599] based on the max_retries setting.
Max retries can be configured using the ChartMogul configuration object.

Retry requests on certain statuses and allow config [ch3381]

---

chartmogul-ruby.gemspec

Fixes: 
WARNING:  pessimistic dependency on webmock (~> 3.4.2, development) may be overly strict

Update webmock version spec

---

fixtures/vcr_cassettes/ChartMogul_Subscription/_update_cancellation_dates/when_array_has_time_objects/is_setting_the_cancellation_dates_of_the_subscription.yml
fixtures/vcr_cassettes/ChartMogul_Subscription/_update_cancellation_dates/when_array_includes_invalid_entries/raises_an_exception.yml
fixtures/vcr_cassettes/ChartMogul_Subscription/_update_cancellation_dates/when_array_includes_valid_entries/is_setting_the_cancellation_dates_of_the_subscription.yml
fixtures/vcr_cassettes/ChartMogul_Subscription/_update_cancellation_dates/when_array_is_empty/makes_an_API_call_and_removes_the_cancellation_dates.yml
lib/chartmogul/subscription.rb
spec/chartmogul/subscription_spec.rb

Problem: `set_cancellation_dates method` on Subscriptions doesn't actually invoke the relevant API call (https://github.com/chartmogul/chartmogul-ruby/blob/master/lib/chartmogul/subscription.rb#L16)
Suggested Solution:
I cannot make the setter send an API request to set the cancellation dates because it will generate unexpected API requests. Also, it is used in various ways and it is not the expected behavior.
I added an update_cancellation_dates for that purpose. 
We will need to update our documentation and make sure the setter is used only for setting the object attributes. That's the intended behavior.

Subscription cancellation dates method issue [ch9984]

---

lib/chartmogul/concerns/entries.rb

Hi! I've noticed that the documentation [on the ChartMogul API website](https://dev.chartmogul.com/v1.0/reference#delete-a-data-source) shows an example of using method `DataSources#last`, but this method is not defined.
This PR defines it. 
Thanks for the great library!

add #last method to Entries

---

chartmogul-ruby.gemspec
fixtures/vcr_cassettes/ChartMogul_Customer/API_Interactions/updates_custom_attributes.yml
lib/chartmogul/customer.rb
lib/chartmogul/enrichment/customer.rb
lib/chartmogul/utils/json_parser.rb
lib/chartmogul/version.rb
spec/chartmogul/utils/json_parser_spec.rb

Using `Time.parse` for general strings is problematic, because it just tries too hard to parse a date. So, we should instead only support ISO & RFC standard. Import API returns data in ISO format. Users of library can pass the `Time` objects, keeping custom parsing in their hands or they can parse ISO-formatted string.
Added unit tests and deduplicated the code a bit. The VCR was updated only after manually checking what Import API currently returns (it's been a while since recorded).

String parsed as time [ch15731]

---

lib/chartmogul/invoice.rb
lib/chartmogul/version.rb
spec/chartmogul/customer_invoices_spec.rb

Added Invoice public property `customer_external_id` to support the parameter for invoices#create action

Allow customer_external_id field

---

changelog.md
fixtures/vcr_cassettes/ChartMogul_CustomerInvoices/API_Interactions/correctly_interracts_with_the_API.yml
fixtures/vcr_cassettes/ChartMogul_Invoice/API_Interactions/returns_all_invoices_through_list_all_endpoint.yml
fixtures/vcr_cassettes/ChartMogul_Subscription/API_Interactions/correctly_interracts_with_the_API.yml
lib/chartmogul/line_items/subscription.rb
lib/chartmogul/subscription.rb
lib/chartmogul/version.rb
spec/chartmogul/invoice_spec.rb
spec/chartmogul/line_items/subscription_spec.rb
spec/chartmogul/subscription_spec.rb

This PR allows for support for subscription sets. It adds a `subscription_set_external_id` attribute to the following objects.
1. `ChartMogul::LineItems::Subscription`
2. `ChartMogul::Subscription`
As I couldn't find the test account used for the VCR specs, I updated the JSON response manually in the vcr fixtures.
It also bumps the version to `1.4.0` as a minor release 
>  MINOR version when you add functionality in a backwards-compatible manner

Add support for subscription sets [ch16168]

---

fixtures/vcr_cassettes/ChartMogul_Ping/pings/and_fails_with_500_internal_server_error.yml
fixtures/vcr_cassettes/ChartMogul_Ping/pings/and_fails_with_504_gateway_timeout_error.yml
lib/chartmogul.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/errors/server_error.rb
spec/chartmogul/ping_spec.rb

for 500..504 response codes.
As example for rescue in background job unlike common ChartMogul::ChartMogulError.

Separate ChartMogul::ServerError exception class 

---

changelog.md
chartmogul-ruby.gemspec
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/correctly_handles_a_422_error.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/deletes_a_plan_group.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/retrieves_existing_plan_group_by_uuid.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/returns_an_array_of_plan_groups.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/updates_existing_plan_group_name.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/updates_existing_plan_group_plans.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroups_Plans/API_interactions/given_a_plan_group_uuid_returns_an_array_of_plans_in_the_plan_group.yml
lib/chartmogul.rb
lib/chartmogul/plan_group.rb
lib/chartmogul/plan_groups/plans.rb
lib/chartmogul/version.rb
spec/chartmogul/plan_group_spec.rb
spec/chartmogul/plan_groups/plans_spec.rb

This PR introduces two new classes:
1. `ChartMogul::PlanGroup`
2. `ChartMogul::PlanGroups::Plans`. 
It allows you to carry out the following operations on plans groups:
1. create
2. retrieve
3. update
4. destroy 
5. list
Additionally, you can list all plans in a given plan group.

Implement support for PlanGroup CRUD actions [ch19221]

---

.travis.yml
chartmogul-ruby.gemspec
lib/chartmogul/version.rb

`faraday` has released version 1.0.0, however we're not compatible yet, so I'd first do one release with latest pre-1.0.0 version.
The other dependencies are test-only.
Upgrade requested by @pcraston here: #67

Upgrade to faraday < 1.0.0 [ch20034]

---

fixtures/vcr_cassettes/ChartMogul_APIResource/connection/works_in_a_threaded_environment.yml
fixtures/vcr_cassettes/ChartMogul_APIResource/connection/works_when_credentials_are_updated.yml
lib/chartmogul/api_resource.rb
lib/chartmogul/config_attributes.rb
lib/chartmogul/version.rb
spec/chartmogul/api_resource_spec.rb
spec/chartmogul/retry_spec.rb

`@connection` class variable in `ChartMogul::APIResource` caching connection credentials which lead to an unexpected result if credentials are changed in runtime. This PR makes `@connection` threadsafe and clears it if credentials are changed.

Make connection thread safe

---

fixtures/vcr_cassettes/ChartMogul_Customer/API_Interactions/updates_customer_using_class_method.yml
fixtures/vcr_cassettes/ChartMogul_Plan/API_Interactions/updates_existing_plan_using_class_method.yml
fixtures/vcr_cassettes/ChartMogul_PlanGroup/API_interactions/updates_existing_plan_group_name_via_class_method.yml
lib/chartmogul/api/actions/update.rb
lib/chartmogul/version.rb
spec/chartmogul/customer_spec.rb
spec/chartmogul/plan_group_spec.rb
spec/chartmogul/plan_spec.rb

**Reason For Change**
Ruby client does not support making direct update requests to the Import API. It allows you to perform update requests only after you fetch the entity from Import API as shown in `Current Behaviour` below. This leads to making 2 requests even if you have `customer_uuid` cached/persisted in the integration code.
**Impacted types of users**
Import API consumers using the `chartmogul-ruby` client library, at the moment need to either make a request for the entity before updating or construct the entity explicitly and then issue `update!`
**Current behaviour**
From API reference 
```ruby
customer = ChartMogul::Customer.retrieve("cus_dummy_uuid")  # makes 1 request
customer.city = "San Francisco"
customer.country = "US"
<... reducing changes for brevity ...> …
```

Add support for direct update requests [ch23601]

---

lib/chartmogul.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/configuration.rb
lib/chartmogul/version.rb
spec/chartmogul/configuration_spec.rb
spec/chartmogul/connection_cache_spec.rb
spec/chartmogul/retry_spec.rb
spec/spec_helper.rb

Adds a new configuration attribute `api_base` for overriding default API base endpoint. 
If no value is set it uses `ChartMogul::API_BASE` so existing apps using the client won't be affected.

Add support for changing domain [ch23946]

---

chartmogul-ruby.gemspec

[Even ruby 2.4 is now at EOL](https://www.ruby-lang.org/en/downloads/branches/), so we can safely enforce it in the gemspec, I think.
Required version 0 is not true :)

Ruby required >= 2.3

---

chartmogul-ruby.gemspec
lib/chartmogul/api_resource.rb

Upgrading faraday gem to `~> 1.0.0` 
In v1 the previous `Faraday::ClientError` has been split for 5xx HTTP Status codes into `Faraday::ServerError`. I've updated error handling for this change. Won't be affecting integrations which use our SDK. 
https://github.com/lostisland/faraday/blob/master/UPGRADING.md#faraday-10

Upgrade faraday gem [ch20108]

---

.gitignore
lib/chartmogul/utils/json_parser.rb
lib/chartmogul/version.rb
spec/chartmogul/utils/json_parser_spec.rb

I rewrited code that should parse timestamp to ISO8601 and RFC2822 to make it works stable and fallback to string if there is anything other then timestamp. Previous code was buggy.
Ticket URL https://app.clubhouse.io/chartmogul/story/21317/incorrect-customer-attribute-returned-by-ruby-gem
P.S. I can't reproduce bug from ticket.

Incorrect customer attribute returned by Ruby Gem [ch21317]

---

changelog.md
fixtures/vcr_cassettes/ChartMogul_Customer/API_Interactions/adds_custom_attributes.yml
fixtures/vcr_cassettes/ChartMogul_Customer/API_Interactions/updates_custom_attributes.yml
lib/chartmogul/api/actions/create.rb
lib/chartmogul/api/actions/custom.rb
lib/chartmogul/api/actions/retrieve.rb
lib/chartmogul/api/actions/update.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/customer.rb
lib/chartmogul/utils/json_parser.rb
lib/chartmogul/version.rb
spec/chartmogul/customer_spec.rb
spec/chartmogul/utils/json_parser_spec.rb

Previously all response keys were converted to snake case by default. This meant that if response returns {"Summary": {...}} as json, it would be converted to {summary: {}} ruby Hash. Presumably this functionality was added to uniformly set instance attributes.
This doesn't completely work for Customer. Customer resource allows setting custom attributes via `add_custom_attributes!`. A user can pass and arbitrary key. However, if a camel case attribute is passed (e.g. `CustomField`) it will be converted to a snake case (`custom_field`) and set to the `custom_attributes` hash of the instance. Therefore the next call to `update!` method will fail because the server is not able to match custom attributes with different cases (`custom_field` with `CustomField`).
This PR fixes the problem by …

Disable response keys conversion for Customer resource

---

changelog.md
fixtures/vcr_cassettes/ChartMogul_Customer/API_Interactions/correctly_interracts_with_the_API.yml
lib/chartmogul/api/actions/all.rb
lib/chartmogul/api/actions/create.rb
lib/chartmogul/api/actions/custom.rb
lib/chartmogul/api/actions/retrieve.rb
lib/chartmogul/api/actions/update.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/customer.rb
lib/chartmogul/utils/hash_snake_caser.rb
lib/chartmogul/utils/json_parser.rb
lib/chartmogul/version.rb
spec/chartmogul/customer_spec.rb
spec/chartmogul/utils/hash_snake_caser_spec.rb
spec/chartmogul/utils/json_parser_spec.rb

Currently, the Gem converts JSON parsed from response bodies to attributes of the various Ruby objects. Because all the object attributes are snake-cased, we used to snake-case all the JSON keys before using them to set the attributes on the model.
However, that caused issues with custom attributes, because we would snake-case the keys. In order to avoid that, we started skipping this for the customer object.
However, the JSON response for the customer object contains both snake-cased keys (`lead_created_at`) as well as keys with a dash (`billing-system-type`).
This meant that attributes such as `billing-system-type` or `customer-since` weren't being set on the Ruby object.
Therefore, this PR would propose having an array of `immutable_keys` for each Object, which by default is an empty …

Provide immutable keys for custom attributes [ch28502]

---

README.md
lib/chartmogul.rb
lib/chartmogul/config_attributes.rb
spec/chartmogul/configuration_spec.rb

This should solve issues like #105, where users don't actually want thread-safety, but easy global configuration.
This change is backwards compatible in the sense that it keeps current behavior and reintroduces the old one under a prefix.
Hopefully this will make the library easier to set up in the common use case of just one-account integration.

Global config [ch30752]

---

changelog.md
fixtures/vcr_cassettes/ChartMogul_Metrics_ActivitiesExport/get_activities_export.yml
fixtures/vcr_cassettes/ChartMogul_Metrics_ActivitiesExport/post_activities_export.yml
lib/chartmogul.rb
lib/chartmogul/metrics/activities_export.rb
lib/chartmogul/version.rb
spec/chartmogul/metrics/activities_export_spec.rb

This PR provides support for a new async activities export:
```
activities_export = ChartMogul::Metrics::ActivitiesExport.create!(
start_date: Time.parse('2020-01-01').to_s,
end_date: Time.parse('2020-12-31').to_s,
type: 'new_biz'
)
```
Initially, the export will have the status `pending` and a `nil` file_url. After a period of time, the async job will complete and the status will update to `processing` and then `succeeded` or `failed`. In the case of `succeeded`, the `file_url` will be populated with the url with the zipped activities export.
In the success case, you'd get something like:
```
#<ChartMogul::Metrics::ActivitiesExport:0x00007fcb4a9ee950
@created_at="2021-07-09T14:37:32+00:00",
@expires_at="2021-07-16T14:37:43+00:00",
@file_url= …
```

Add async activities export [ch32201]

---

fixtures/vcr_cassettes/ChartMogul_Metrics_ActivitiesExport/post_activities_export.yml
spec/chartmogul/metrics/activities_export_spec.rb

The spec in spec/chartmogul/metrics/activities_export_spec.rb:8 was failing in local development environment because of time zone mismatch between the local environment and timestamp set in vcr cassette.

Pass dev env failing spec by fixing timezone of timestamp [ch32201]

---

changelog.md
lib/chartmogul/api_resource.rb
spec/chartmogul/api_resource_spec.rb

Shortcut ticket: https://app.shortcut.com/chartmogul/story/35959/include-client-version-header-in-library-ruby
This adds header to every single request that will look something like this:
```
'User-Agent': 'chartmogul-ruby/3.0.0'
```

Add user agent with lib version [ch35959]

---

.github/workflows/test.yml
changelog.md
chartmogul-ruby.gemspec
lib/chartmogul.rb
lib/chartmogul/api_resource.rb
lib/chartmogul/version.rb

This change adds support for Faraday 2.7 - see related issue here: https://github.com/chartmogul/chartmogul-ruby/issues/134

[sc-50895] Upgrade Faraday

---

fixtures/vcr_cassettes/ChartMogul_SubscriptionEvent/API_interactions/creates_a_new_subscription_event_through_initialization.yml
lib/chartmogul/subscription_event.rb
lib/chartmogul/version.rb
spec/chartmogul/subscription_event_spec.rb

The reason why including the `API::Actions::Create` module in this API resource `SubscriptionEvent` fails to send a proper request to our API is that this endpoint requires that the request is in the format of:
```json
{ "subscription_event": { "key": "value" } }
```
The other endpoints don't have this, so there the code we have for `.create!` works correctly as it takes every attribute and passes it on to the JSON to be sent, but here we have to nest it first. This is why instead of adapting the existing module `ChartMogul::API::Actions::Create` I decided to just copy it here and make the small change required instead.

fix creating SubscriptionEvent through .create!(attrs)

---

4.0-Upgrade.md
README.md
changelog.md
lib/chartmogul/version.rb

This adds an upgrade guide like we have in the other libraries for updating from v3.x to v4.x.

add upgrade guide from v3.x to v4.x

---

lib/chartmogul/customer.rb
spec/chartmogul/customer_spec.rb
spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/creates_the_customer_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/retrieves_the_customer_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/updates_customer_correctly_with_the_class_method.yml

Support website_url field in customer model. Adjusted tests and data manually. I didn't recreate the VCR cassettes using the actual API.

Add customer website_url field

---

lib/chartmogul/metrics/customers/subscription.rb
spec/chartmogul/metrics/customers/subscriptions_spec.rb

Add `:uuid` field for metrics/customer/subscription resource. Tested manually using bin/console.

Support uuid attribute for subscription resource

---

.gitignore
lib/chartmogul/csv/line_items/one_time.rb
lib/chartmogul/csv/line_items/subscription.rb
lib/chartmogul/csv/line_items/trial.rb

Files for `Trial` & `Subscription` were defining the same constant (b'c it was at the module level), this moves it into the class. It would be a breaking change, but it's the `alpha` branch :man_shrugging:

Fix constant duplication

---

changelog.md
lib/chartmogul.rb
lib/chartmogul/customer.rb
lib/chartmogul/task.rb
lib/chartmogul/version.rb
spec/chartmogul/customer_spec.rb
spec/chartmogul/task_spec.rb
spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/creates_a_task_belonging_to_the_customer_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Customer/API_Actions/lists_the_tasks_belonging_to_the_customer_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Task/API_Actions/creates_a_task_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Task/API_Actions/destroys_the_task_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Task/API_Actions/retrieves_a_task_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Task/API_Actions/retrieves_all_tasks_correctly.yml
spec/fixtures/vcr_cassettes/ChartMogul_Task/API_Actions/updates_the_task_correctly_with_the_class_method.yml
spec/fixtures/vcr_cassettes/ChartMogul_Task/API_Actions/with_pagination/paginates_correctly.yml

This PR adds support for the Tasks API to the SDK.
The spec for this project can be found [here](https://www.notion.so/chartmogul/API-for-Tasks-c87a8c8de97d495a92bf7266c49ff6ec).
**Create a task for a customer**
```ruby
customer = ChartMogul::Customer.retrieve('cus_3819e09a-50a2-11ee-ada7-9fcf71cd4580')
customer.create_task({ ... })
```
**List all tasks for a customer**
```ruby
customer = ChartMogul::Customer.retrieve('cus_3819e09a-50a2-11ee-ada7-9fcf71cd4580')
customer.tasks
```
**Get all tasks**
```ruby
tasks = ChartMogul::Task.all(customer_uuid: customer_uuid)
```
**Get a task**
```ruby
task = ChartMogul::Task.retrieve('task_uuid')
```
**Create a task**
```ruby
new_task = ChartMogul::Task.create({ customer_uuid: customer_uuid, ... })
```
**Update a task**
```ruby
updated_task = …
```

Add Tasks API support to Ruby Client [sc-66752]

---

lib/chartmogul.rb
lib/chartmogul/csv/mrr_interval_edit.rb
spec/chartmogul/csv/mrr_interval_edit_spec.rb

Adds a mapping for `mrr_interval_edits` which will be used by the generic import tool (see https://github.com/chartmogul/platform/pull/26485)

Add MrrIntervalEdit to CSV module
